import localFont from "next/font/local";
import "./globals.css";
import LeftNav from "@/components/nav/nav";
import HamburgerMenu from "@/components/HamburgerMenu.js/HamburgerMenu";
import NavBarMobile from "@/components/NavBarMobile/NavBarMobile";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased transition-colors duration-300 bg-zinc-300 dark:bg-zinc-900`}
      >
        <LeftNav />
        <NavBarMobile/>
        {children}
      </body>
    </html>
  );
}
